/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.samdwise.gui;

import com.samdwise.action.CafeAction;
import com.samdwise.to.CafeTO;
import java.text.SimpleDateFormat;
import java.util.Calendar;

/**
 *
 * @author samdwise
 */
public class CafeMainGui extends javax.swing.JFrame {
    double [] drink = new double[5];
    double [] cake = new double[8];
    double [] saleCost = new double[3];
    double [] calVariable = new double[10];
    
    CafeTO cafe = new CafeTO();
    CafeAction action = new CafeAction();

    /**
     * Creates new form ResturantMainGui
     */
    public CafeMainGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jCheckBoxLagosCake = new javax.swing.JCheckBox();
        jCheckBoxBaltimoreCake = new javax.swing.JCheckBox();
        jCheckBoxNewYorkCake = new javax.swing.JCheckBox();
        jCheckBoxMarylandCake = new javax.swing.JCheckBox();
        jCheckBoxIndianCake = new javax.swing.JCheckBox();
        jCheckBox1PoliceCake = new javax.swing.JCheckBox();
        jCheckBoxQueensCake = new javax.swing.JCheckBox();
        jCheckBoxBlackCake = new javax.swing.JCheckBox();
        jTextFieldBaltimoreCake = new javax.swing.JTextField();
        jTextFieldPoliceCake = new javax.swing.JTextField();
        jTextFieldMarylandCake = new javax.swing.JTextField();
        jTextFieldIndianCake = new javax.swing.JTextField();
        jTextFieldBlackCake = new javax.swing.JTextField();
        jTextFieldLagosCake = new javax.swing.JTextField();
        jTextFieldQueenCake = new javax.swing.JTextField();
        jTextFieldNewYorkCake = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jCheckBoxCoffee = new javax.swing.JCheckBox();
        jCheckBoxIceTea = new javax.swing.JCheckBox();
        jCheckBoxIceCream = new javax.swing.JCheckBox();
        jCheckBoxLattle = new javax.swing.JCheckBox();
        jCheckBoxTea = new javax.swing.JCheckBox();
        jTextFieldCoffee = new javax.swing.JTextField();
        jTextFieldIceTea = new javax.swing.JTextField();
        jTextFieldLattle = new javax.swing.JTextField();
        jTextFieldTea = new javax.swing.JTextField();
        jTextFieldIceCream = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaReceipt = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCostDrinks = new javax.swing.JTextField();
        jTextFieldCostCakes = new javax.swing.JTextField();
        jTextFieldServiceCharge = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jButtonTotal = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldTotal = new javax.swing.JTextField();
        jTextFieldSubTotal = new javax.swing.JTextField();
        jTextFieldTax = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1370, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.blue, 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckBoxLagosCake.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBoxLagosCake.setText("Lagos Cake");
        jCheckBoxLagosCake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxLagosCakeMouseClicked(evt);
            }
        });
        jPanel2.add(jCheckBoxLagosCake, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jCheckBoxBaltimoreCake.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBoxBaltimoreCake.setText("Baltimore Cake");
        jCheckBoxBaltimoreCake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxBaltimoreCakeMouseClicked(evt);
            }
        });
        jPanel2.add(jCheckBoxBaltimoreCake, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jCheckBoxNewYorkCake.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBoxNewYorkCake.setText("New York Cake");
        jCheckBoxNewYorkCake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxNewYorkCakeMouseClicked(evt);
            }
        });
        jPanel2.add(jCheckBoxNewYorkCake, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jCheckBoxMarylandCake.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBoxMarylandCake.setText("Maryland Cake");
        jCheckBoxMarylandCake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxMarylandCakeMouseClicked(evt);
            }
        });
        jCheckBoxMarylandCake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMarylandCakeActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBoxMarylandCake, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jCheckBoxIndianCake.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBoxIndianCake.setText("Indian Cake");
        jCheckBoxIndianCake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxIndianCakeMouseClicked(evt);
            }
        });
        jPanel2.add(jCheckBoxIndianCake, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jCheckBox1PoliceCake.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox1PoliceCake.setText("Police Cake");
        jCheckBox1PoliceCake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox1PoliceCakeMouseClicked(evt);
            }
        });
        jPanel2.add(jCheckBox1PoliceCake, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jCheckBoxQueensCake.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBoxQueensCake.setText("Queen's Cake");
        jCheckBoxQueensCake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxQueensCakeMouseClicked(evt);
            }
        });
        jPanel2.add(jCheckBoxQueensCake, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jCheckBoxBlackCake.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBoxBlackCake.setText("Black Cake");
        jCheckBoxBlackCake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxBlackCakeMouseClicked(evt);
            }
        });
        jPanel2.add(jCheckBoxBlackCake, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jTextFieldBaltimoreCake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldBaltimoreCake.setText("0");
        jPanel2.add(jTextFieldBaltimoreCake, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 176, -1));

        jTextFieldPoliceCake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPoliceCake.setText("0");
        jPanel2.add(jTextFieldPoliceCake, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 176, -1));

        jTextFieldMarylandCake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldMarylandCake.setText("0");
        jPanel2.add(jTextFieldMarylandCake, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 176, -1));

        jTextFieldIndianCake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldIndianCake.setText("0");
        jPanel2.add(jTextFieldIndianCake, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 176, -1));

        jTextFieldBlackCake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldBlackCake.setText("0");
        jPanel2.add(jTextFieldBlackCake, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 176, -1));

        jTextFieldLagosCake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldLagosCake.setText("0");
        jPanel2.add(jTextFieldLagosCake, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 176, -1));

        jTextFieldQueenCake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldQueenCake.setText("0");
        jPanel2.add(jTextFieldQueenCake, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 176, -1));

        jTextFieldNewYorkCake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldNewYorkCake.setText("0");
        jPanel2.add(jTextFieldNewYorkCake, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 176, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 340, 250));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.blue, 2));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Cafe Management Systems");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\samdwise\\Downloads\\Restaurant-Blue-icon2.png")); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 30, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\samdwise\\Downloads\\Chef-2-icon.png")); // NOI18N
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 80, 60));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1160, 80));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.blue, 2));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckBoxCoffee.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBoxCoffee.setText("Coffee");
        jCheckBoxCoffee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxCoffeeMouseClicked(evt);
            }
        });
        jCheckBoxCoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCoffeeActionPerformed(evt);
            }
        });
        jPanel4.add(jCheckBoxCoffee, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 29, -1, -1));

        jCheckBoxIceTea.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBoxIceTea.setText("Ice Tea");
        jCheckBoxIceTea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxIceTeaMouseClicked(evt);
            }
        });
        jPanel4.add(jCheckBoxIceTea, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 64, -1, -1));

        jCheckBoxIceCream.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBoxIceCream.setText("Ice Cream");
        jCheckBoxIceCream.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxIceCreamMouseClicked(evt);
            }
        });
        jPanel4.add(jCheckBoxIceCream, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 99, -1, -1));

        jCheckBoxLattle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBoxLattle.setText("Lattle");
        jCheckBoxLattle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxLattleMouseClicked(evt);
            }
        });
        jPanel4.add(jCheckBoxLattle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 134, -1, -1));

        jCheckBoxTea.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBoxTea.setText("Tea");
        jCheckBoxTea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxTeaMouseClicked(evt);
            }
        });
        jPanel4.add(jCheckBoxTea, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 164, -1, -1));

        jTextFieldCoffee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCoffee.setText("0");
        jTextFieldCoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCoffeeActionPerformed(evt);
            }
        });
        jPanel4.add(jTextFieldCoffee, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 31, 176, -1));

        jTextFieldIceTea.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldIceTea.setText("0");
        jPanel4.add(jTextFieldIceTea, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 66, 176, -1));

        jTextFieldLattle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldLattle.setText("0");
        jPanel4.add(jTextFieldLattle, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 136, 176, -1));

        jTextFieldTea.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldTea.setText("0");
        jPanel4.add(jTextFieldTea, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 166, 176, -1));

        jTextFieldIceCream.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldIceCream.setText("0");
        jPanel4.add(jTextFieldIceCream, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 101, 176, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 410, 250));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.blue, 2));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextAreaReceipt.setColumns(20);
        jTextAreaReceipt.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTextAreaReceipt.setRows(5);
        jScrollPane1.setViewportView(jTextAreaReceipt);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 15, 372, 390));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 100, 390, 420));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.blue, 2));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Cost Of Drinks");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Cost of Cakes");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Service Charge");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 144, -1, -1));

        jTextFieldCostDrinks.setEditable(false);
        jTextFieldCostDrinks.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldCostDrinks.setText("0");
        jPanel6.add(jTextFieldCostDrinks, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 48, 82, -1));

        jTextFieldCostCakes.setEditable(false);
        jTextFieldCostCakes.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldCostCakes.setText("0");
        jPanel6.add(jTextFieldCostCakes, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 95, 78, -1));

        jTextFieldServiceCharge.setEditable(false);
        jTextFieldServiceCharge.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldServiceCharge.setText("0");
        jPanel6.add(jTextFieldServiceCharge, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 142, 78, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 240, 250));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.blue, 2));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonTotal.setText("Total");
        jButtonTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTotalActionPerformed(evt);
            }
        });
        jPanel7.add(jButtonTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Receipt");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 530, 390, 80));

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.blue, 2));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Tax");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 50, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Sub Total");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 100, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Total");
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 144, -1, -1));

        jTextFieldTotal.setEditable(false);
        jTextFieldTotal.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldTotal.setText("0");
        jPanel8.add(jTextFieldTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 142, 365, -1));

        jTextFieldSubTotal.setEditable(false);
        jTextFieldSubTotal.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldSubTotal.setText("0");
        jPanel8.add(jTextFieldSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 95, 365, -1));

        jTextFieldTax.setEditable(false);
        jTextFieldTax.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldTax.setText("0");
        jPanel8.add(jTextFieldTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 48, 365, -1));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 510, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxMarylandCakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMarylandCakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxMarylandCakeActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTextFieldCostDrinks.setText("0");
        jTextFieldCostCakes.setText("0");
        jTextFieldServiceCharge.setText("0");
        jTextFieldSubTotal.setText("0");
        jTextFieldTax.setText("0");
        jTextFieldTotal.setText("0");
        jTextFieldTea.setText("0");
        jTextFieldQueenCake.setText("0");
        jTextFieldPoliceCake.setText("0");
        jTextFieldMarylandCake.setText("0");
        jTextFieldLattle.setText("0");
        jTextFieldLagosCake.setText("0");
        jTextFieldIndianCake.setText("0");
        jTextFieldIceTea.setText("0");
        jTextFieldIceCream.setText("0");
        jTextFieldCoffee.setText("0");
        jTextFieldBaltimoreCake.setText("0");
        jTextFieldBlackCake.setText("0");
        jTextFieldNewYorkCake.setText("0");
        jTextAreaReceipt.setText(null);
        jTextFieldCostCakes.setText("0");
        jTextFieldCostDrinks.setText("0");
        jTextFieldServiceCharge.setText("0");
        jCheckBox1PoliceCake.setSelected(false);
        jCheckBoxBaltimoreCake.setSelected(false);
        jCheckBoxBlackCake.setSelected(false);
        jCheckBoxCoffee.setSelected(false);
        jCheckBoxIceCream.setSelected(false);
        jCheckBoxIceTea.setSelected(false);
        jCheckBoxIndianCake.setSelected(false);
        jCheckBoxLagosCake.setSelected(false);
        jCheckBoxLattle.setSelected(false);
        jCheckBoxMarylandCake.setSelected(false);
        jCheckBoxNewYorkCake.setSelected(false);
        jCheckBoxQueensCake.setSelected(false);
        jCheckBoxTea.setSelected(false);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        action.printReceipt(cafe);
        jTextAreaReceipt.append(cafe.getReceipt());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCheckBoxCoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCoffeeActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jCheckBoxCoffeeActionPerformed

    private void jTextFieldCoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCoffeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCoffeeActionPerformed

    private void jCheckBoxCoffeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxCoffeeMouseClicked
        // TODO add your handling code here:
        cafe.setCostOfDrinks(jTextFieldCostDrinks.getText());     
        String returnValue = action.returnIndividualCost(cafe.getCostOfDrinks(), jTextFieldCoffee.getText(), jCheckBoxCoffee.isSelected());
        jTextFieldCoffee.setText(returnValue);
        cafe.setCoffee(returnValue);
    }//GEN-LAST:event_jCheckBoxCoffeeMouseClicked

    private void jCheckBoxIceTeaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxIceTeaMouseClicked
        // TODO add your handling code here:
        cafe.setCostOfDrinks(jTextFieldCostDrinks.getText());
        String returnValue = action.returnIndividualCost(cafe.getCostOfDrinks(), jTextFieldIceTea.getText(), jCheckBoxIceTea.isSelected());
        jTextFieldIceTea.setText(returnValue);
        cafe.setIceTea(returnValue);
    }//GEN-LAST:event_jCheckBoxIceTeaMouseClicked

    private void jCheckBoxIceCreamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxIceCreamMouseClicked
        // TODO add your handling code here:
        cafe.setCostOfDrinks(jTextFieldCostDrinks.getText());        
        String returnValue = action.returnIndividualCost(cafe.getCostOfDrinks(), jTextFieldIceCream.getText(), jCheckBoxIceCream.isSelected());
        jTextFieldIceCream.setText(returnValue);
         cafe.setIceCream(returnValue);
    }//GEN-LAST:event_jCheckBoxIceCreamMouseClicked

    private void jCheckBoxLattleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxLattleMouseClicked
        // TODO add your handling code here:
        cafe.setCostOfDrinks(jTextFieldCostDrinks.getText());
              
        String returnValue = action.returnIndividualCost(cafe.getCostOfDrinks(),jTextFieldLattle.getText(), jCheckBoxLattle.isSelected());
        jTextFieldLattle.setText(returnValue);
        cafe.setLattle(returnValue);
    }//GEN-LAST:event_jCheckBoxLattleMouseClicked

    private void jCheckBoxTeaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxTeaMouseClicked
        // TODO add your handling code here:
        cafe.setCostOfDrinks(jTextFieldCostDrinks.getText());
       
        
        String returnValue = action.returnIndividualCost(cafe.getCostOfDrinks(), jTextFieldTea.getText(), jCheckBoxTea.isSelected());
        jTextFieldTea.setText(returnValue);
        cafe.setTea(returnValue);
        
    }//GEN-LAST:event_jCheckBoxTeaMouseClicked

    private void jButtonTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTotalActionPerformed
        // TODO add your handling code here:
        cafe.setTax("0");
        action.costOfDrinks(cafe);
        action.costOfCakes(cafe);
        action.total(cafe);
        action.subTotal(cafe);
        jTextFieldCostDrinks.setText(cafe.getCostOfDrinks());
        jTextFieldCostCakes.setText(cafe.getCostOfCakes());
        jTextFieldTax.setText(cafe.getTax());
        jTextFieldServiceCharge.setText(cafe.getServiceCharge());
        jTextFieldSubTotal.setText(cafe.getSubTotal());
        jTextFieldTotal.setText(cafe.getTotal());
    }//GEN-LAST:event_jButtonTotalActionPerformed

    private void jCheckBoxLagosCakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxLagosCakeMouseClicked
        // TODO add your handling code here:
        cafe.setCostOfCakes(jTextFieldCostCakes.getText());
        String returnValue = action.returnIndividualCost(cafe.getCostOfCakes(), jTextFieldLagosCake.getText(), jCheckBoxLagosCake.isSelected());
        jTextFieldLagosCake.setText(returnValue);
        cafe.setLagosCake(returnValue);
        
    }//GEN-LAST:event_jCheckBoxLagosCakeMouseClicked

    private void jCheckBoxBaltimoreCakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxBaltimoreCakeMouseClicked
        // TODO add your handling code here:
        cafe.setCostOfCakes(jTextFieldCostCakes.getText());
        String returnValue = action.returnIndividualCost(cafe.getCostOfCakes(), jTextFieldBaltimoreCake.getText(), jCheckBoxBaltimoreCake.isSelected());
        jTextFieldBaltimoreCake.setText(returnValue);
        cafe.setBaltimoreCake(returnValue);
    }//GEN-LAST:event_jCheckBoxBaltimoreCakeMouseClicked

    private void jCheckBoxNewYorkCakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxNewYorkCakeMouseClicked
        // TODO add your handling code here:
        cafe.setCostOfCakes(jTextFieldCostCakes.getText());
        String returnValue = action.returnIndividualCost(cafe.getCostOfCakes(), jTextFieldNewYorkCake.getText(), jCheckBoxNewYorkCake.isSelected());
        jTextFieldNewYorkCake.setText(returnValue);
        cafe.setNewYorkCake(returnValue);
    }//GEN-LAST:event_jCheckBoxNewYorkCakeMouseClicked

    private void jCheckBoxMarylandCakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxMarylandCakeMouseClicked
        // TODO add your handling code here:
        cafe.setCostOfCakes(jTextFieldCostCakes.getText());
        String returnValue = action.returnIndividualCost(cafe.getCostOfCakes(), jTextFieldMarylandCake.getText(), jCheckBoxMarylandCake.isSelected());
        jTextFieldMarylandCake.setText(returnValue);
        cafe.setMarylandCake(returnValue);
    }//GEN-LAST:event_jCheckBoxMarylandCakeMouseClicked

    private void jCheckBoxIndianCakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxIndianCakeMouseClicked
        // TODO add your handling code here:
        cafe.setCostOfCakes(jTextFieldCostCakes.getText());
        String returnValue = action.returnIndividualCost(cafe.getCostOfCakes(), jTextFieldIndianCake.getText(), jCheckBoxIndianCake.isSelected());
        jTextFieldIndianCake.setText(returnValue);
        cafe.setIndianCake(returnValue);
    }//GEN-LAST:event_jCheckBoxIndianCakeMouseClicked

    private void jCheckBoxBlackCakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxBlackCakeMouseClicked
        // TODO add your handling code here:
        cafe.setCostOfCakes(jTextFieldCostCakes.getText());
        String returnValue = action.returnIndividualCost(cafe.getCostOfCakes(), jTextFieldBlackCake.getText(), jCheckBoxBlackCake.isSelected());
        jTextFieldBlackCake.setText(returnValue);
        cafe.setBlackCake(returnValue);
    }//GEN-LAST:event_jCheckBoxBlackCakeMouseClicked

    private void jCheckBox1PoliceCakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox1PoliceCakeMouseClicked
        // TODO add your handling code here:
        cafe.setCostOfCakes(jTextFieldCostCakes.getText());
        String returnValue = action.returnIndividualCost(cafe.getCostOfCakes(), jTextFieldPoliceCake.getText(), jCheckBox1PoliceCake.isSelected());
        jTextFieldPoliceCake.setText(returnValue);
        cafe.setPoliceCake(returnValue);
    }//GEN-LAST:event_jCheckBox1PoliceCakeMouseClicked

    private void jCheckBoxQueensCakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxQueensCakeMouseClicked
        // TODO add your handling code here:
        cafe.setCostOfCakes(jTextFieldCostCakes.getText());
        String returnValue = action.returnIndividualCost(cafe.getCostOfCakes(), jTextFieldQueenCake.getText(), jCheckBoxQueensCake.isSelected());
        jTextFieldQueenCake.setText(returnValue);
        cafe.setQueensCake(returnValue);
    }//GEN-LAST:event_jCheckBoxQueensCakeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CafeMainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CafeMainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CafeMainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CafeMainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CafeMainGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonTotal;
    private javax.swing.JCheckBox jCheckBox1PoliceCake;
    private javax.swing.JCheckBox jCheckBoxBaltimoreCake;
    private javax.swing.JCheckBox jCheckBoxBlackCake;
    private javax.swing.JCheckBox jCheckBoxCoffee;
    private javax.swing.JCheckBox jCheckBoxIceCream;
    private javax.swing.JCheckBox jCheckBoxIceTea;
    private javax.swing.JCheckBox jCheckBoxIndianCake;
    private javax.swing.JCheckBox jCheckBoxLagosCake;
    private javax.swing.JCheckBox jCheckBoxLattle;
    private javax.swing.JCheckBox jCheckBoxMarylandCake;
    private javax.swing.JCheckBox jCheckBoxNewYorkCake;
    private javax.swing.JCheckBox jCheckBoxQueensCake;
    private javax.swing.JCheckBox jCheckBoxTea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaReceipt;
    private javax.swing.JTextField jTextFieldBaltimoreCake;
    private javax.swing.JTextField jTextFieldBlackCake;
    private javax.swing.JTextField jTextFieldCoffee;
    private javax.swing.JTextField jTextFieldCostCakes;
    private javax.swing.JTextField jTextFieldCostDrinks;
    private javax.swing.JTextField jTextFieldIceCream;
    private javax.swing.JTextField jTextFieldIceTea;
    private javax.swing.JTextField jTextFieldIndianCake;
    private javax.swing.JTextField jTextFieldLagosCake;
    private javax.swing.JTextField jTextFieldLattle;
    private javax.swing.JTextField jTextFieldMarylandCake;
    private javax.swing.JTextField jTextFieldNewYorkCake;
    private javax.swing.JTextField jTextFieldPoliceCake;
    private javax.swing.JTextField jTextFieldQueenCake;
    private javax.swing.JTextField jTextFieldServiceCharge;
    private javax.swing.JTextField jTextFieldSubTotal;
    private javax.swing.JTextField jTextFieldTax;
    private javax.swing.JTextField jTextFieldTea;
    private javax.swing.JTextField jTextFieldTotal;
    // End of variables declaration//GEN-END:variables
}
